version: '3'
services:
    schoolcycode:
        build: .
        ports: 
        - "8080:80"
        - "8081:443"
        environment: 
            ASPNETCORE_URLS: "http://+"  #  "https://+;http://+"
            ASPNETCORE_HTTPS_PORT: "8081"
            ASPNETCORE_ENVIRONMENT: "Development"
            # volumes:
            # - C:\Users\rea\AppData\Roaming\Microsoft\UserSecrets\:/root/.microsoft/usersecrets
            # - ${HOME}/.aspnet/https:/root/.aspnet/https/
    
    postgres:
        image: postgres:10.5
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5438:5432'
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

