version: '3'
services:
    schoolcycode:
        build: .
        ports: 
        - "8080:80"
        - "8081:443"
        environment: 
            ASPNETCORE_URLS: "https://+;http://+"
            ASPNETCORE_HTTPS_PORT: "8081"
            ASPNETCORE_ENVIRONMENT: "Development"
        volumes:
            - C:\Users\rea\AppData\Roaming\Microsoft\UserSecrets\:/root/.microsoft/usersecrets
            - C:\Users\rea\.aspnet\https:/root/.aspnet/https/
        