version: '3'
services:
    schoolcycode:
        build: .
        ports: 
        - "8080:80"
        - "8081:443"
        environment: 
            ASPNETCORE_URLS: "http://+"  #  "https://+;http://+"
            ASPNETCORE_HTTPS_PORT: "8081"
            ASPNETCORE_ENVIRONMENT: "Development"
            # volumes:
            # - C:\Users\rea\AppData\Roaming\Microsoft\UserSecrets\:/root/.microsoft/usersecrets
            # - ${HOME}/.aspnet/https:/root/.aspnet/https/
    
    sql-server-db:
      container_name: sql-server-db
      image: mcr.microsoft.com/mssql/server
      ports:
        - "1433:1433"
      environment:
        SA_PASSWORD: "pa55w0rd!"
        ACCEPT_EULA: "Y"

